### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by LeoColomb**
@ozh Is it possible to sign up for the GitHub Action beta? Thx!

https://github.com/features/actions/signup/?account=YOURLS

### CODE REVIEW

**Comment by dgw** [comment]
@LeoColomb It might take a _long_ time to get the YOURLS org enabled. I signed up very early, and got actions on my personal repos pretty soon, but my orgs did not start getting enabled until the last month or two.

**Comment by LeoColomb** [comment]
@dgw I'm ready to wait! 😉

**Comment by ozh** [comment]
"You now have access to GitHub Actions!" -- should be ok then

**Comment by LeoColomb** [comment]
@ozh Amazing, thanks!

**Pull request merged**
